# datasource
spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# Logging
logging:
  level:
    org.hibernate.sql: debug

# Swagger
springdoc:
  packages-to-scan: com.study.signin.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

# JWT
jwt:
  secret: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
  expire-time: 1800000